### ISSUE TITLE
training scripts and training data

### ISSUE THREAD

**Issue by Elfsong** [dwadden/multivers#1]
Hi @dwadden, could you share the training scripts and data of LongCheaker?

**Comment by dwadden** [comment]
Hi, sorry for the delay, I'll try to get the code cleaned up and added to the repo in the next couple weeks. If you need it sooner, email me at `dwadden@cs.washington.edu` and we can figure something out.

**Comment by Elfsong** [comment]
Hi @dwadden, I have emailed dwadden@cs.washington.edu about two weeks. Looking forward to hearing from you.

**Comment by dwadden** [comment]
Hi,

I'll do my best to get the training scripts posted over the weekend. Sorry for the delay.

I can't find an email separate from this GitHub thread. Did you send a separate email?

Dave

**Comment by Elfsong** [comment]
Yes, I send a separate email. 
Don't worry, take your time.

**Comment by Elfsong** [comment]
Hi David, do you have any progress on it?

**Comment by DakeZhang1998** [comment]
@dwadden Hi David, I am also eagerly looking forward to your training code.

**Comment by dwadden** [comment]
Hi all, sorry for the delay, I'll try my best to get this done this week.

**Comment by Elfsong** [comment]
Cannot trust you anymore...

**Comment by dwadden** [comment]
I apologize, and understand your frustration. I will reopen this ticket if the situation changes.

**Comment by dwadden** [comment]
Training code is finally available. See [here](https://github.com/dwadden/multivers/blob/main/doc/training.md) for details. Sorry if this is too late to be useful.
