### ISSUE TITLE
Release on HF Hub

### ISSUE THREAD

**Issue by janheinrichmerker** [dwadden/multivers#11]
To make it easier to use the MultiVerS chekpoints, it would be nice to have them published on the Hugging Face Hub.
Ideally, we could then just load the model from the Transformers library. But I'm not sure if that's possible or even intended.

**Comment by Rubywong123** [comment]
Agreed.
Can't figure out the reason, but my downloading speed is quite low (~100KB/s). I wonder if there's a speed limitation?

**Comment by dwadden** [comment]
You're right, this would be a good thing to do! I'm on vacation and will take a look when I get back.

**Comment by dwadden** [comment]
Revisiting this now. I'm sorry, I think I'm probably not going to have the bandwidth to publish on Huggingface. I'd certainly welcome a contribution to do this, if you think it would be convenient for your work!
