### ISSUE TITLE
MultiVerS training data link inaccessible 

### ISSUE THREAD

**Issue by athrvkk** [dwadden/multivers#12]
It seems that the link provided in the code is currently inaccessible (https://github.com/dwadden/multivers/blob/main/script/get_data_train.sh). 

I would be extremely grateful if you could provide me with access to the training data or offer any alternative means to obtain it. 

Thanks!

**Comment by nazaninjafar** [comment]
I am having similar issue.

**Comment by fateme-hshm96** [comment]
Hey @dwadden! Could you kindly share a new link for the train data, please? I would really appreciate it. Thanks! 🙏

**Comment by dwadden** [comment]
Sorry for the delay. Here's what happened: I recently finished my PhD, and so I had to migrate the Google Drive associated with my school (UW) over to my personal account. During the migration, some files were lost. Unfortunately, the lost files include the training data. I just wrote IT to see if we can recover the files. If not, our best bet might be to find someone else who has downloaded the training data already and who can send it back to me.
I'll post updates here. Sorry about this.

**Comment by nazaninjafar** [comment]
Hey @dwadden I think I can help you with the training data. I downloaded it before and can send it back to you.

**Comment by dwadden** [comment]
I managed to recover the data. The scripts are fixed now. If you run `script/get_train_data.sh`, the download should work. Let me know if this isn't the case.

**Comment by athrvkk** [comment]
I am able to download the data now!
Thank you so much for your efforts. I really appreciate it!
