### ISSUE TITLE
Models license

### ISSUE THREAD

**Issue by janheinrichmerker** [dwadden/multivers#2]
To be able to use your pre-trained models in other projects and research, could you please add an open license for the model files?
I'd prefer Creative Commons because it is very open and allows for modification of your files (e.g., fine-tuning): https://creativecommons.org/choose/

**Comment by janheinrichmerker** [comment]
Also see #3

**Comment by dwadden** [comment]
Thanks for the suggestion, I just added a LICENSE file. I've used the MIT license in the past, so I just stuck with that. Let me know if this doesn't work and I can change it.

**Comment by janheinrichmerker** [comment]
Yes, that should work, thank you very much!
