### ISSUE TITLE
Source code license

### ISSUE THREAD

**Issue by janheinrichmerker** [dwadden/multivers#3]
To be able to use (and reproduce) your code in other projects, could you please add an open source license to this repository?
There are several good options to choose from: https://choosealicense.com/

**Comment by janheinrichmerker** [comment]
Also see #2

**Comment by dwadden** [comment]
Just responded in your other issue, let me know if this works!

**Comment by janheinrichmerker** [comment]
Thank you! MIT license should be fine!
