### ISSUE TITLE
About train.py

### ISSUE THREAD

**Issue by CEclipse** [dwadden/multivers#4]
Hi,@dwadden 

And i have a question,how could i get the
 
import lib.longformer.data as dm
from lib.longformer.model import SciFactModel
on train.py，i haven’t found the module named lib.longformer

and by the way did u train the model on scifact,covidfact, Healthver and fever datasets?

Looking forward your reply
best regards

**Comment by dwadden** [comment]
Hi,

I'm going to post the data preprocessing code and training code soon (next few weeks). I'm very sorry for the delay, I've had a few other projects I've needed to wrap up.

As for your first question, did you do `conda develop .` on the project root folder?

Dave

**Comment by CEclipse** [comment]
Hi，
I didn‘t do conda develop. on the project root folder. If I do this step , could I get the  
lib.longformer.data as dm
from lib.longformer.model import SciFactModel
 lib.longformer module on train.py?
Looking forward your reply

**Comment by dwadden** [comment]
I'm sorry I missed this. I'm not sure I understand your issue? If things still aren't working, could you post a minimal example with the code you're trying to run and the bug you're getting when you try to run it?

**Comment by helena-lena** [comment]
Hi, I want to ask the same question.
I followed all instructions and did "conda develop ." on the project root folder.
When I run "longchecker/train.py" to finetune the scifact dataset from the checkpoint, I get an error as below.
![error](https://user-images.githubusercontent.com/72365222/208353131-56bbb0ac-22f4-4b3a-8849-2fc4d7c2a824.png)
How can I import the 'lib.longformer' module?

**Comment by dwadden** [comment]
Hi,

I'm sorry about this, I still haven't gotten the training code cleaned up yet. I'll post here when that's changed.

Dave

**Comment by dwadden** [comment]
Training code is now working! See [here](https://github.com/dwadden/multivers/blob/main/doc/training.md) for details. let me know if you've got more questions.

**Comment by helena-lena** [comment]
Thank you for sharing the training code!😊

**Comment by dwadden** [comment]
You're welcome! Sorry it took so long.
