### ISSUE TITLE
Adapting dataset for pre-train 

### ISSUE THREAD

**Issue by VulnDetector** [dwadden/multivers#6]
Hi, @dwadden ,I finished reading the paper of the multivers,I consider multivers a great job for scientific claim verification.
And also,I suppose that to pre-train on several dataset really matters. So, I mean, can you provide the code about how to transfer the origin form of the dataset into the one which can be used for pretraining.
To be more specific,I wanna know how to transfer `Fever`,`EVIDENCEINFERENCE`,`PUBMEDQA` from origin form to what you use in pretraining.
Besides, I'm wondering if you can also provide the code for pre-train.
Thanks a lot!

**Comment by dwadden** [comment]
Hi,

Apologies that I've been so slow on providing the pretraining data. I'll try to get things posted in the next few weeks.

Dave

**Comment by dwadden** [comment]
Hi,

Training code is added now. See [here](https://github.com/dwadden/multivers/blob/main/doc/training.md) for details. Let me know if you've got more questions!

Dave
